#ipynb 코랩 시작

In [1]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [2]:
tf.executing_eagerly()

True

In [3]:
a = tf.constant([[1,2],[3,4]])
print(a)
print(a.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]


In [7]:
x = [[2.]]
m = tf.matmul(x, x)
print(m)
print(m.numpy())

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
[[4.]]


In [11]:
matrix1 = tf.constant([[1.,2.], [3.,4.]])
matrix2 = tf.constant([[2.,0.], [1.,2.]])

gop = tf.matmul(matrix1, matrix2)
print(gop.numpy())

[[ 4.  4.]
 [10.  8.]]


In [12]:
gop = tf. matmul(matrix2, matrix1)
print(gop.numpy())

[[ 2.  4.]
 [ 7. 10.]]


In [13]:
x = tf.constant([[0],[10],[20],[30]])
y = tf.constant([0,1,2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [14]:
import numpy as np

print(np.arange(3))
print(np.ones((3,3)))
print()

x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [15]:
a = tf.constant([[1,2], [3,4]])
b = tf.add(a,1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [16]:
c = np.multiply(a,b)
print(c)

[[ 2  6]
 [12 20]]


In [17]:
my_image = tf.zeros([2,5,5,3])
my_image.shape

TensorShape([2, 5, 5, 3])

In [18]:
tf.rank(my_image)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [19]:
rank_three_tensor = tf.ones([3,4,5])
rank_three_tensor.shape

TensorShape([3, 4, 5])

In [20]:
rank_three_tensor.numpy()

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

In [22]:
matrixAlt = tf.reshape(matrixB,[4,3,-1])
matrixAlt

NameError: ignored

In [23]:
float_tensor = tf.cast(tf.constant([1,2,3]), dtype=tf.float32)
float_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [24]:
float_tensor.dtype

tf.float32

In [25]:
v = tf.Variable(0.0)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>

In [28]:
w = v +10 
w

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [29]:
w.numpy()

10.0

In [32]:
v = tf.Variable(2.0)
v.assign_add(5)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=7.0>

In [33]:
v.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>